### ISSUE TITLE
Create repo TODO list

### ISSUE THREAD

**Issue by mpostol** [mpostol/UA-Nodeset#4]
All related work to prepare the repository for further development.

Follow [community recommended standards](https://opensource.guide/)

## Scope:

- [x] .gitignore
- [x] Repository description
- [x] social preview
community-health-file)
- [x] sponsor button
- [x] Make release
- [x] Add license file
- [x]  Code of conduct
- [x]  Contributing or use [default one](https://help.github.com/en/github/building-a-strong-community/creating-a-default
- [x] README.md
- [x] Wiki or GitHub pages
- [x] Info in the master project if applicable

**Comment by mpostol** [comment]
Info in the master project if applicable moved to the master project note to be fixed as independent issues.
